### ISSUE TITLE
Random freeze while playing and in menu

### ISSUE THREAD

**Issue by ghost** [hker9527/ChuniControl#2] opened 2020-05-03 05:33 UTC
The input would drop randomly while playing the game and air seems to make the app unresponsive. Usually when freeze, the app will have a green background, but the app can freeze without green background too.
![Screenshot_20200503-114730_ChuniControl 1](https://user-images.githubusercontent.com/10580981/80899434-4268b780-8d3a-11ea-8dec-4b5a2956948f.jpg)
![Screenshot_20200503-120538_ChuniControl 1](https://user-images.githubusercontent.com/10580981/80899436-4c8ab600-8d3a-11ea-9b78-edf2fae0a016.jpg)

**Comment by hker9527** [comment] 2020-05-03 06:38
It should be related to AIR detection algorithm since the background will turn green when an AIR instrction is active. When a finger reached a velocity threshold the relative button will be released and turned to an AIR instrction. I am thinking of making the top area specifically for AIR. 

About the freezing problem I can't seem to reproduce.

**Comment by ghost** [comment] 2020-05-03 07:05
I tried playing again with USB tethering, the problem is less frequent but there is still freezing. After relaunching the app the latency that it reports is over 1s. Maybe latency is the issue? AIR still freeze when activate though. I don't know if the device I'm playing on is a problem but I'm using Samsung Galaxy S8+.

**Comment by ghost** [comment] 2020-05-03 14:39
I tested the app on another device, same issue. It seems like the freeze happens whenever I drag on the screen.

**Comment by reflexyG** [comment] 2020-05-04 08:32
Same.. The app only freeze when I slide (but it's on older version) For new version, it freeze randomly when I touch or slides, and 
the app then force stopped...  Tested on two devices, same situation.

**Comment by hker9527** [comment] 2020-05-04 16:59
If you can checkout the logcat (by using adb) and grepping the output of my app, you can see what inputs are being detected. Maybe it could help to identify when it will freeze.

**Comment by ghost** [comment] 2020-05-05 09:48
[log.txt](https://github.com/hker9527/ChuniControl/files/4579999/log.txt)
Here is the log, there is so much log in one second though.

**Comment by hker9527** [comment] 2020-05-14 07:27
Maybe it's related to my method to send packets.

https://github.com/hker9527/ChuniControl/blob/1946600e13b5f0dcde5c018de88c855848c5473f/app/src/main/java/com/bckps7336/chunicontrol/ClientThread.java#L81-L85

https://github.com/hker9527/ChuniControl/blob/1946600e13b5f0dcde5c018de88c855848c5473f/app/src/main/java/com/bckps7336/chunicontrol/ClientThread.java#L157-L177

Let me try to use a queue to store all packets and popping them to the sender.

**Comment by hker9527** [comment] 2020-08-04 19:59
b45bfe6eda2b62d266d686376a69aa9b6a84af8a

**Comment by hker9527** [comment] 2020-08-04 20:01
Plz also update the CHUNIIO Library, as I re-adapted the original slider countring way.

**Comment by ghost** [comment] 2020-08-05 12:22
Now working fine on S8+. Closing the issue.

**Closed as completed** 2020-08-05 12:22 UTC
Labels: bug
